### ISSUE TITLE
loadcv with no argument fails

### ISSUE THREAD

**Issue by jslavin** [planetarymike/IDL-Colorbars#3]
When I do
IDL> loadcv
I get:
% Compiled module: LOADCV.
% Compiled module: LOADCSVCOLORBAR.
% Variable is undefined: COLORTBL.
% Execution halted at: LOADCSVCOLORBAR    50
   /export/slavin/IDL-Colorbars/loadcsvcolorbar.pro
%                      LOADCV              3
   /export/slavin/IDL-Colorbars/loadcv.pro
%                      $MAIN$

loadcv, 80 (or other numbers)
works fine.
I'm running IDL 8.9.0 on Linux.
Maybe IDL has changed the way it treats non-keyword arguments? I don't use it much any more.
In any case, thanks for this package. I'm trying to get colleagues of mine who use IDL to start using better color maps.

**Comment by planetarymike** [comment]
Thanks for using the package, @jslavin --- what behavior do you expect if `loadcv` is called without any argument? Should it load a default colormap, such as 78?

**Comment by jslavin** [comment]
In the README it says:
To load a set of qualitative colors and a colorbar from file, use the command

loadcv
You can specify the filename of a colorbar CSV file, relative to the IDL_rgb_values directory, or call it without arguments and see a list of all the colorbar files hosted in this directory, and select which one to load by number.

So based on that, I figured that calling it without arguments would show me a list of all the colorbar files.

**Comment by planetarymike** [comment]
Thanks--- it's been a while since I looked at this code and I didn't remember the original intent or consult the readme before asking (oops!). This should be fixed by #4 .
